### ISSUE TITLE
Coordinate with Letsencrypt whether it is possible to use LE certificates for public testbeds

### ISSUE THREAD

**Issue by berendt** [osism/testbed#1019]

**Comment by fkr** [comment]
Aside from the constraints from the LE 'Subscribers Agreement' another reason that speaks against the initial idea is that the LE private key can be used to revoke a certificate via the LE api. As such: it should not be exposed.
Discussion can be seen here: https://community.letsencrypt.org/t/storing-of-issued-cert-keys-demo-setup/170035/14

**Comment by berendt** [comment]
We will use self-signed certificates.
