### ISSUE TITLE
Remove Swift endpoint

### ISSUE THREAD

**Issue by berendt** [osism/testbed#1030]
Everyone uses the object storage directly via the S3 API from the Ceph RGW. The Swift keystone endpoint is not used by anyone.

**Comment by berendt** [comment]
Discuss this first in the SCS Team 1 weekly meeting.

**Comment by berendt** [comment]
This is needed for the conformance tests and should therefore be left in.

**Comment by Nils98Ar** [comment]
@berendt @ppkuschy Are the buckets created via ceph or openstack/horizon/skyline?

**Comment by berendt** [comment]
Via the OpenStack integration at the moment.

**Comment by Nils98Ar** [comment]
Ok!
