### ISSUE TITLE
Document how to import the internal testbed CA on a workstation

### ISSUE THREAD

**Issue by berendt** [osism/testbed#1038]
- for Linux
- for MacOS
- for Windows

**Comment by berendt** [comment]
@matfechner  asks Plusserver if someone can do it for Windows

**Comment by tibeer** [comment]
> @matfechner asks Plusserver if someone can do it for Windows

@berendt iirc a ca import on windows is done by double-clicking the file and confirming the import ^^

**Comment by osfrickler** [comment]
I'm not sure whether this documentation wouldn't be actually out of scope for the testbed docs. There are too many options depending on the exact client setup, like things may change between different distros or even different releases of them. Also I wouldn't advise importing the certificate globally, instead add it to the browser when needed and use the ca_cert option for the openstack client.

Documenting some specific option like

```
cp /opt/configuration/environments/kolla/certificates/ca/testbed.crt /usr/local/share/ca-certificates/
update-ca-certificates
```

could be in conflict with a lot of security policies, so I would suggest to stay away from that. In the longer run we should instead provide the option for deployments to use a custom domain for which they can generate their own certificates.

**Comment by berendt** [comment]
Let's document that a self-signed CA is used and where to find it. The rest should be left to the reader.
