### ISSUE TITLE
openstack: use the openstack.cloud collection in the bootstrap playbooks

### ISSUE THREAD

**Issue by berendt** [osism/testbed#1100]
https://github.com/openstack/ansible-collections-openstack
https://docs.ansible.com/ansible/latest/collections/openstack/cloud/index.html

The collection is already usable in the osism-ansible runtime environment.

Replace all os_ tasks with the corresponding openstack.cloud tasks.

Also make the collection available where required:

```
  collections:
    - openstack.cloud

  tasks:
    ....
```

**Comment by osfrickler** [comment]
Closed by https://github.com/osism/testbed/pull/1106
