### ISSUE TITLE
Testbed (main) does not finish deployment

### ISSUE THREAD

**Issue by amachowiak** [osism/testbed#1143]
Hi,

yeterday afternoon I started a "make deploy-identity" which hasn't finished yet.

Last lines from output:
ok: [testbed-node-1.testbed.osism.xyz] => (item=enable_multipathd_False)
ok: [testbed-node-1.testbed.osism.xyz] => (item=enable_murano_False)
ok: [testbed-node-1.testbed.osism.xyz] => (item=enable_neutron_True)
ok: [testbed-node-1.testbed.osism.xyz] => (item=enable_nova_True)
ok: [testbed-node-1.testbed.osism.xyz] => (item=enable_octavia_True)

Ansible-playbook processes:
dragon@testbed-manager:~$ ps -ef | grep ansible-playbook
dragon    156879  156877  7 Mar24 ?        01:14:49 /usr/bin/python3 /usr/local/bin/ansible-playbook --vault-password-file /opt/configuration/environments/.vault_pass -e CONFIG_DIR=/opt/configuration/environments/kolla -e @/opt/configuration/environments/configuration.yml -e @/opt/configuration/environments/secrets.yml -e @secrets.yml -e @images.yml -e @configuration.yml -e kolla_action=deploy /ansible/kolla-mariadb.yml
dragon    156935  156879  0 Mar24 ?        00:00:00 /usr/bin/python3 /usr/local/bin/ansible-playbook --vault-password-file /opt/configuration/environments/.vault_pass -e CONFIG_DIR=/opt/configuration/environments/kolla -e @/opt/configuration/environments/configuration.yml -e @/opt/configuration/environments/secrets.yml -e @secrets.yml -e @images.yml -e @configuration.yml -e kolla_action=deploy /ansible/kolla-mariadb.yml

Kind regards,
Andre.

**Comment by berendt** [comment]
Maybe ``deploy-identity`` is broken. i'll test it.

At least the overall deployment works. The daily testbed deployments are green.

**Comment by amachowiak** [comment]
Works like a charm. Thank you!

Should this fix also pushed into stable branch as well?

**Comment by berendt** [comment]
The stable branch is currently not up to date and is not tested. But it is a good point. I will create an issue to revive the stable branch.

**Comment by amachowiak** [comment]
Thank you
