### ISSUE TITLE
Issue with "make deploy-identity"

### ISSUE THREAD

**Issue by amachowiak** [osism/testbed#1162]
Hi,

I have discovere several issues when running "make deploy-identity".

Steps to reproduce:
make deploy-identity
make ssh
make wireguard
(configure tunnel locally)

### Horizon does not work
https://api.testbed.osism.xyz
-> Login via default Keystone Credentials (admin:password): You are not authorized to access this page Login

### Login via Keycloak does not work
https://keycloak.testbed.osism.xyz
Login with admin:passwd
Create new User demo, leave all defaults, add password
Login via https://api.testbed.osism.xyz -> Keycloak -> Change password -> HTTP/401 "The request you have made requires authentication."

### Operations dashboard does not work
With respect to README.md in https://github.com/osism/testbed I might expect operations dashboard, however it doesn't.
I think the link is broken (still port 8080), but port 80 oder 443 also do not work. Am I expected to run a special osism apply command to make it work?

### TLS/SSL works only for Firefox
Feedback for new SSL/TLS implementation: Firefox works, but Safari and Chrome refuses to work with selfsigned wildcard certs. A hint would be helpful how to make those browsers work with testbed. Those issues are quite kinda frustrating if things do not work at all after a deployment.

Kind regards,
Andre.

**Comment by berendt** [comment]
Thanks for the input. It would be nice if you would open a single issue per topic in the future. I have split it out now and am closing this issue.

**Comment by amachowiak** [comment]
Try to do so. Wasn't sure which issues are located in front of my keyboard or in testbed though :)

**Comment by berendt** [comment]
It is also always good to report the "front of my keyboard" issues. Then others can find them too. And we can try to document it.
