### ISSUE TITLE
[identity] Horizon does not work

### ISSUE THREAD

**Issue by berendt** [osism/testbed#1164]
```
https://api.testbed.osism.xyz/
-> Login via default Keystone Credentials (admin:password): You are not authorized to access this page Login
```

Split from #1162

**Comment by berendt** [comment]
Login with Keystone credentials works fine.

The ``You are not authorized to access this page [Login](https://api.testbed.osism.xyz/auth/login/)`` note is ok.

By default, a dashboard is displayed that accesses Nova, among other things. Since this is not present in the Identity testbed, this error occurs.

I add a screenshot to the documentation.

![Bildschirmfoto 2022-04-05 um 11 42 48](https://user-images.githubusercontent.com/419091/161726487-7abcbc51-0eb4-4d9f-a472-4c317658d39e.png)

**Comment by amachowiak** [comment]
Documentation (https://docs.osism.tech/testbed/deployment.html#initialization) states: "Use deploy-identity to deploy identity services when building the environment. This also includes all required infrastructure services."
I had expected Nova to work.

Actually, I am not sure which components get rolled out on which Makefile target without looking into the source code.
