### ISSUE TITLE
Feature Req: terraform testbed should use uniq keypair names

### ISSUE THREAD

**Issue by frosty-geek** [osism/testbed#1207]
When you're deploying multiple testbeds with the same Openstack User you will run into the Issue that the keypair name is not uniq

**Comment by frosty-geek** [comment]
@matfechner

**Comment by reqa** [comment]
I propose to document this in [the deployment docs](https://docs.osism.de/testbed/deployment.html) (or document the technical details at some more suitable location and just add a notice with a link).

**Comment by berendt** [comment]
This is already solved:

```
resource "openstack_compute_keypair_v2" "key" {
  name = var.prefix
}
```

You can simply use the prefix variable to give the testbeds different names.

I'm documenting it.
