### ISSUE TITLE
Keycloak Cert expired

### ISSUE THREAD

**Issue by matfechner** [osism/testbed#1296]
Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number:
            5a:8b:4a:3b:f2:68:de:20:fc:1d:ae:d6:d1:12:71:85:a2:18:dc:d0
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = DE, ST = NI, O = Internet Widgits Pty Ltd, CN = univention
        Validity
            Not Before: Apr 22 14:47:07 2021 GMT
            Not After : Apr 22 14:47:07 2022 GMT
        Subject: C = DE, ST = NI, O = Internet Widgits Pty Ltd, CN = univention

**Comment by reqa** [comment]
The SSL certificate https://github.com/osism/testbed/tree/main/environments/custom/files/keycloak is expired. Either we need to create a new one, possibly with a longer validity range or we generate the certificates during rollout and let them be signed by the CA in an automated way. -  I don't know how we currently handle this for other certs in the testbed.

**Comment by reqa** [comment]
See also proposals at https://github.com/osism/testbed/issues/1282

**Comment by berendt** [comment]
@matfechner Arvid has documented how to exchange the certificate. Why didn't you do that directly?

I am now adapting this so that we also take our wildcard certificate here.
