### ISSUE TITLE
testbed deployment: document minimum versions for terraform and ansible

### ISSUE THREAD

**Issue by garloff** [osism/testbed#1337]
My first attempt to do the new ansible based deployment failed due to some obscure ansible error.
```
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "ansible-galaxy collection install --force \"/home/linux/src/github.com/osism/ansibl
e-collection-commons\"\nansible-galaxy collection install --force \"/home/linux/src/github.com/osism/ansible-collection-services\"\n", "delt
a": "0:00:02.823792", "end": "2022-09-12 16:34:23.906085", "msg": "non-zero return code", "rc": 1, "start": "2022-09-12 16:34:21.082293", "stderr": "ERROR! Invalid collection name '/home/linux/src/github.com/osism/ansible-collection-commons', name must be in the format <namespace>.<collection>. Please make sure namespace and collection name contains characters from [a-zA-Z0-9_] only.\nERROR! Invalid collection name '/home/linux/src/github.com/osism/ansible-collection-services', name must be in the format <namespace>.<collection>. Please make sure namespace and collection name contains characters from [a-zA-Z0-9_] only.", "stderr_lines": ["ERROR! Invalid collection name '/home/linux/src/github.com/osism/ansible-collection-commons', name must be in the format <namespace>.<collection>. Please make sure namespace and collection name contains characters from [a-zA-Z0-9_] only.", "ERROR! Invalid collection name '/home/linux/src/github.com/osism/ansible-collection-services', name must be in the format <namespace>.<collection>. Please make sure namespace and collection name contains characters from [a-zA-Z0-9_] only."], "stdout": "Process install dependency map\n|\bProcess install dependency map\n|\b", "stdout_lines": ["Process install dependency map", "|\bProcess install dependency map", "|\b"]}
```
I guessed that my ansible (2.9.x) was too old and after pip installing ansible-2.11, I was more successful.
Looking at the documentation, I could not find a minimum version of ansible and terraform though.
I guess we need terraform-1.0.x and ansible-2.11.x at least.

**Comment by berendt** [comment]
We mention in the docs that the current versions must be usable. This means Ansible 6.x and Terraform 1.2.x. I'll add that to the docs.

**Comment by garloff** [comment]
OK, thanks. The 2.11 version that I suggested referred to ansible-core (and was ansible-4), looks like ansible-6 has ansible-core-2.13. (The 4/2.11 version seemed to fail the same way as the 6/2.13 did now, so it looks to me like we don't currently necessarily need the latest and greatest, but I understand that we may not be able to validate that and thus recommend ansible-6/2.13.)

**Comment by berendt** [comment]
It may be that older versions also work. However, we only test Ansible 6.x in the CI. Accordingly, we can only list this in the documentation. It also makes sense to always use the latest stable version of Ansible.
