### ISSUE TITLE
make the new ansible testbed rollout not depend on ~/src/github.com/osism

### ISSUE THREAD

**Issue by frosty-geek** [osism/testbed#1359]
ref: https://docs.osism.tech/testbed/preparations.html

The testbed should not be dependent whether the git repo is checked out to this hard coded directory as it was before the ansible deployment move

**Comment by berendt** [comment]
It's not hardcoded. You can set the paths via the ``basepath`` and the ``repo_path`` parameters.

Will document the parameters @ https://docs.osism.tech/testbed/requirements.html#this-repository.
