### ISSUE TITLE
playbooks/deploy.yml depends on hard coded ~/venv/bin/ansible-galaxy

### ISSUE THREAD

**Issue by frosty-geek** [osism/testbed#1362]
deploy.yml depends on hard coded ~/venv/bin/ansible-galaxy which is not mentioned in neither https://docs.osism.tech/testbed/requirements.html or https://docs.osism.tech/testbed/preparations.html

**Comment by berendt** [comment]
It's not hardcoded, you can set an other location via ``-e ansible_galaxy=/path/to/ansible-galaxy``.  Should be documented.

**Comment by berendt** [comment]
Use of ``ansible_galaxy `` and ``ansible_playbook`` parameters already documented @ https://docs.osism.tech/testbed/deployment.html.
