### ISSUE TITLE
Update wildcard and manager certificate

### ISSUE THREAD

**Issue by berendt** [osism/testbed#1402]
Related to [osism/testbed/issues/1390#issuecomment-1322262879](https://github.com/osism/testbed/issues/1390#issuecomment-1322262879)

**Comment by osfrickler** [comment]
The actual issue with the mentioned commit is that the manager certificate needs to be updated in some less obvious locations. I'll do that and try to also update the docs accordingly.

**Comment by reqa** [comment]
> The actual issue with the mentioned commit is that the manager certificate needs to be updated in some less obvious locations. I'll do that and try to also update the docs accordingly.

Ok, one additional related point here:

In the testbed /opt/traefik/certificates/default.cert currently contains a certificate for a "OSISM Testbed CA" which is different from the general "OSISM Testbed CA" cert deployed everywhere in the testbed ([here](https://github.com/osism/testbed/blob/main/environments/kolla/certificates/ca/testbed.crt) and  [here](https://github.com/osism/testbed/blob/main/environments/openstack/testbed.pem)). 

It looks like [this change](https://github.com/osism/testbed/commit/5d65088f9fac4b0ba31e041250b2f7ee6973907d) simply missed to update also [this file](https://github.com/osism/testbed/tree/main/environments/custom/files/keycloak) in the repository.

**Comment by berendt** [comment]
Should we merge first and you add a test for it with a separated PR?

**Comment by reqa** [comment]
> Should we merge first and you add a test for it with a separated PR?

I guess that makes sense.

**Comment by berendt** [comment]
Will be done in the later part of the week. I had to fix a few general testbed bugs first so that the deployment does reliably again.
