### ISSUE TITLE
Switch testbed to OpenStack Zed release

### ISSUE THREAD

**Issue by osfrickler** [osism/testbed#1426]

**Comment by frosty-geek** [comment]
when you do this please tag the latest version so we're still able to deploy testbeds for the latest stable release

**Comment by berendt** [comment]
I am currently rebuilding the testbed so that it also works with stable on latest.

**Comment by berendt** [comment]
Done with the new job testbed-deploy-stable. Tag is not necessary. We deploy all jobs from the same base. This ensures that the same configurations work with all versions out there. They all run with a PR now, too.
