### ISSUE TITLE
CiaB: Add instructions how to get networking working

### ISSUE THREAD

**Issue by garloff** [osism/testbed#1431]
A fresh CiaB setup has no external network set up that instances can use.
This means there is no way that freshly started instances can access the network that the CiaB is located in nor the internet.
Please document how external networks / provider networks can be set up. Links to upstream docu are fine of course.
(And no, I have not figured this out yet myself ...)

**Comment by berendt** [comment]
Nothing more to do. The VLAN101 for external connectivity now works out of the box.
