### ISSUE TITLE
Documentation: How to create Images

### ISSUE THREAD

**Issue by ra-beer** [osism/testbed#1432]
Document how to create and upload images and ink this to CiaB.
https://github.com/osism/cloud-in-a-box/issues/23

**Comment by osfrickler** [comment]
What do you mean by "creating images", building custom cloud images from scratch? What would be the use case for that?

Also I'm not sure that "upload images" belongs here, there is nothing testbed-specific about it. Maybe this could better be part of the general docs in some "OpenStack for Du^W^WUser Quickstart Guide"?

**Comment by berendt** [comment]
In the SCS team call we agreed to include a few general QuickStart things here in the testbed documentation. It is about uploading images, creating flavours etc.

**Comment by garloff** [comment]
The CiaB system now comes with a Cirros 0.6.0 (why not 0.6.1?) and an Ubuntu 22.04 image.
The latter only lacks a `provided_until` property to be compliant to the SCS image metadata spec.
(I would also not promise the `uuid_validity` `forever`, as this does not seem realistic. `last-3` might be a better default.)
The Cirros image metadata is far away from SCS image metadata conformance.

With one good image, the system would seems useful to me without specific docs on image registration.

**Comment by berendt** [comment]
Newer versions + correct metadata everywhere come when we use 5.0.0 here and then the Image Manager is used to upload the images. That's not possible with 4.2.0 because we do not include the openstack-image-manager there.
