### ISSUE TITLE
Documentation: Add how to create flavors

### ISSUE THREAD

**Issue by ra-beer** [osism/testbed#1433]
Add a guide how to create flavors and link this to the CiaB documentation
https://github.com/osism/cloud-in-a-box/issues/22

**Comment by osfrickler** [comment]
I'm not sure that this belongs here, there is nothing testbed-specific about it. Maybe this could better be part of the general docs in some "OpenStack for Du^W^WUser Quickstart Guide"?

**Comment by berendt** [comment]
In the SCS team call we agreed to include a few general QuickStart things here in the testbed documentation. It is about uploading images, creating flavours etc.

**Comment by garloff** [comment]
There are useful flavors now predefined in testbed, so we don't need to document things anymore.
