### ISSUE TITLE
add a `Contributing.md` document to the repository

### ISSUE THREAD

**Issue by artificial-intelligence** [osism/testbed#1598]
I'm missing some contributor guidelines in this repository:

- must commits be signed of?
- what is the PR workflow, who are contacts for reviews?
- is a CLA required etc.

**Comment by berendt** [comment]
We have https://docs.osism.tech/development.html for this. We can add a Contributing.md and add a link to the docs there.

**Comment by artificial-intelligence** [comment]
will provide a PR for that
