### ISSUE TITLE
Access API/Webinterfaces of testbed from external 

### ISSUE THREAD

**Issue by Nils98Ar** [osism/testbed#1643]
Hi,

what is the current way to do this? Currently I can only login via ssh.

The commands on https://docs.scs.community/docs/testbed/doc/usage do not seem to work:

For VNC:
```
root@testbed-seed:~/src/github.com/osism/testbed# make console ENVIRONMENT=xyz.cloud
make: *** No rule to make target 'console'.  Stop.
```

For tunnel:
```
root@testbed-seed:~/src/github.com/osism/testbed# make sshuttle  ENVIRONMENT=xyz.cloud
make: *** No rule to make target 'sshuttle'.  Stop.
```

The best would be to use routable IPs for the nodes, the kolla_internal_vip_address and the kolla_external_vip_address in my opinion... is this possible somehow?

Best regards
Nils

**Comment by berendt** [comment]
You have to use wireguard.

**Comment by berendt** [comment]
For the mentioned commands: you have to run them inside the terraform directory (The following commands are executed from the testbed/terraform repository directory).

**Comment by Nils98Ar** [comment]
> You have to use wireguard.

Thank you!
