### ISSUE TITLE
Rework overview graphic

### ISSUE THREAD

**Issue by berendt** [osism/testbed#1675]
![](https://docs.scs.community/assets/images/overview-c71c577094be503fc3dbe97bcd6bb951.png)

**Comment by aeroflydesign** [comment]
PNG: 
![overview_structure-and-composition-of-a-Testbed_red](https://github.com/osism/testbed/assets/39653040/c4e6b4b8-e1df-4b03-951b-1fa91fb39f83)

SVG: 
![overview_structure-and-composition-of-a-Testbed_red](https://github.com/osism/testbed/assets/39653040/aebf2c3c-a539-47bb-9b7d-302d0bafa8ac)
