### ISSUE TITLE
testbed-node root partition fills up quickly, mainly due to openstack

### ISSUE THREAD

**Issue by reqa** [osism/testbed#2112]
In my testbed-node-0 the 49GB root partition got filled up to the last byte after a few weeks of deployment. The single most likely candidate seems to be opensearch:

root@testbed-node-0:/home/dragon# du -sh /var/lib/docker/volumes/opensearch/_data/nodes/0/indices/
16G     /var/lib/docker/volumes/opensearch/_data/nodes/0/indices/

root@testbed-node-1:/home/dragon# du -sh /var/lib/docker/volumes/opensearch/_data/nodes/0/indices/
18G     /var/lib/docker/volumes/opensearch/_data/nodes/0/indices/

root@testbed-node-2:/home/dragon# du -sh /var/lib/docker/volumes/opensearch/_data/nodes/0/indices/
16G     /var/lib/docker/volumes/opensearch/_data/nodes/0/indices/

**Comment by reqa** [comment]
Close followers:

root@testbed-node-1:/home/dragon# du -sh /var/lib/docker/volumes/*
4.6G    /var/lib/docker/volumes/kolla_logs
4.0G    /var/lib/docker/volumes/mariadb

**Comment by berendt** [comment]
@reqa I think this is fixed. Please re-open the issue when the root partition still fills up quickly on a fresh deployment.
