### ISSUE TITLE
Error disabling testbed switches during deploy on environment `regiocloud-fast`

### ISSUE THREAD

**Issue by janhorstmann** [osism/testbed#2141]
While deploying on `regiocloud-fast` the setup of the manager errors on [disabling the testbed switches in netbox](https://github.com/osism/testbed/blob/main/scripts/deploy/000-manager-service.sh#L49), because of an unknown `device_id` `dcs-7050tx3-48c8`.

It seems that in this environment disablement of the testbed switches races the creation of the device type. Adding a `sleep 60`  in the script on line 48 works around the issue.

**Comment by berendt** [comment]
I disabled the net box initialisation for the moment.
