### ISSUE TITLE
`make` target `vpn-wireguard` fails for environment `regiocloud-fast`

### ISSUE THREAD

**Issue by janhorstmann** [osism/testbed#2143]
The `make` target `vpn-wireguard` fails for environment `regiocloud-fast` with

```
wg-quick: The config file must be a valid interface name, followed by .conf
```

`wg-quick` uses the part before `.conf` of the config file name as an interface name. The name `regiocloud-fast` exceeds the allowed number of 16 characters for interface names.

[Truncating strings in `make` is cumbersome](https://stackoverflow.com/a/7102253) and might confuse users looking for the config. Maybe it would be easier to rename the environment, but I have not come up with an alternative name yet.

**Comment by berendt** [comment]
Fixed by a36a4f09f530b53980d976e8a6e1ea743861ec4d.
