### ISSUE TITLE
Check barbican/hashicorp vault integration

### ISSUE THREAD

**Issue by berendt** [osism/testbed#237]

**Comment by tibeer** [comment]
@berendt i guess barbican's focus more on OpenStack while hashicorps vault is more open. From a "commonly used" standpoint, hashicorps vault will become adopted more and more and therefore the industry wide standard.

**Comment by berendt** [comment]
Works with stable/xena. Let's check this as optional integration.

**Comment by berendt** [comment]
Stale.
