### ISSUE TITLE
"netbox-netbox-worker-1" stuck in Created state

### ISSUE THREAD

**Issue by Richie1710** [osism/testbed#2427]
the netbox-netbox.worker-1 is stuck in created state 

```
root@testbed-manager:/# docker compose --project-directory /opt/netbox ps --all --format json | jq '. | select(.State=="created" or .State=="exited" or .Health=="starting" or .Health=="unhealthy") | .Name'
"netbox-netbox-worker-1"
```

`a41aa1acf4da   quay.io/osism/netbox:v4.0.9                 "/opt/netbox/venv/bi…"   20 minutes ago   Created                                                                                                           netbox-netbox-worker-1`

docker logs shows no logs

**Comment by berendt** [comment]
Maybe too little memory on the manager node? Cannot reproduce this at the moment. In /opt/netbox try docker compose down and docker compose up -d. I think this is not a problem with the Netbox service itself.

**Comment by Richie1710** [comment]
Load Avarage of: 0.01 0.03 0.05
Memory Used 4.19 od 126 G

steps to reproduce 
`docker compose down` to cleanup

```
docker compose up -d
 ✔ Network netbox_default            Created                                                                       0.1s
 ✔ Container netbox-redis-1          Healthy                                                                      30.9s
 ✔ Container netbox-postgres-1       Healthy                                                                      30.9s
 ✘ Container netbox-netbox-1         Error                                                                       211.6s
 ✔ Container netbox-netbox-worker-1  Created                                                                       0.0s
```
 
 after some additional minutes netbox-netbox-1 is healthy 
 
 worker stays in created state forever now

```
root@testbed-manager:/opt/netbox# docker ps -a | grep netbox-netbox-worker-1
2a200c6116c4   quay.io/osism/netbox:v4.0.10                "/opt/netbox/venv/bi…"   8 minutes ago   Created
                                                                                              netbox-netbox-worker-1
```
                                                                                              
now I can do again  docker compose up -d which is fixing the worker.  I guess problem is here a kind of timeout for netbox itself which is killing docker-compose before its finished          

**working Workaround:** 

- raising startperiod of netbox:healthcheck:start_period to 240              
- adding for worker a start_period of 60 

seems to solve timeing issue for us.      

```
root@testbed-manager:/opt/netbox# docker compose up -d
[+] Running 5/5
 ✔ Network netbox_default            Created                                                                       0.1s
 ✔ Container netbox-redis-1          Healthy                                                                      30.9s
 ✔ Container netbox-postgres-1       Healthy                                                                      30.9s
 ✔ Container netbox-netbox-1         Healthy                                                                     277.6s
 ✔ Container netbox-netbox-worker-1  Started                                                                     277.8s
```

after some additional seconds 

`root@testbed-manager:/opt/netbox# docker compose --project-directory /opt/netbox ps --all --format json | jq '. | select(.State=="created" or .State=="exited" or .Health=="starting" or .Health=="unhealthy") | .Name'`

is responding no lines and all netbox containers are healthy

can you make this timeouts configurable ?

**Comment by Richie1710** [comment]
@berendt The solution described in [this issue](https://github.com/osism/issues/issues/1116) works fine for manual deployments. However, when Netbox is restarted via the systemd service file at /etc/systemd/system/netbox.service, the environment variables are not loaded.

I believe we need to set the environment variables in the systemd unit, as they are not being correctly loaded during the Zuul deployment either. One possible solution could be creating an EnvironmentFile and referencing it in the systemd unit.

**Comment by berendt** [comment]
Which environment variables? These are values that are added in the docker-compose.yml file (e.g. https://github.com/osism/ansible-collection-services/blob/main/roles/netbox/templates/docker-compose.yml.j2#L58-L60).

**Comment by Richie1710** [comment]
But I cannot overwrite them in deployment as 

```
2024-09-04 09:07:17.670515 | ubuntu-jammy | RUNNING HANDLER [osism.services.netbox : Restart netbox service] ***************
2024-09-04 09:07:17.733535 | ubuntu-jammy | skipping: [testbed-manager.testbed.osism.xyz]
```

so always default value is used as systemd job has no option to inject variables with other values

**Comment by berendt** [comment]
Which environment variables do you want to overwrite via the unit file?

**Comment by Richie1710** [comment]
I want to raise the timeout. 
locally I can do now 

```
export netbox_service_netbox_worker_start_period="60s"
export netbox_service_netbox_start_period="240s"
```

but inside of deployment its rebooted via handler 

```
https://github.com/osism/ansible-collection-services/blob/bd8a0786081b5dca18969278649e000903ddbbff/roles/netbox/handlers/main.yml#L2-L14
```

so I cannot override them .

**Comment by berendt** [comment]
netbox_service_netbox_worker_start_period as well as netbox_service_netbox_start_period are Ansible variables that are used in the docker-compose.yml template. You have to add the in your environments/infrastructure/configuration.yml file and re-run osism apply netbox. The unit file is just there to start/stop/restart the Docker compose service via docker compose in the /opt/netbox directory.

**Comment by Richie1710** [comment]
changed values there and tested it. netbox worker is now starting
