### ISSUE TITLE
testbed: playbook_cronjobs.yml fails with operator_user undefined

### ISSUE THREAD

**Issue by garloff** [osism/testbed#390]
`The task includes an option with an undefined variable. The error was: 'operator_user' is undefined.`

And indeed, it is not set anywhere except for terraform/files/node.yml which does not appear to be used.
Logging in and setting operator_user = dragon in environments/ansible.cfg and rerunning the playbook makes it succeed.

**Comment by garloff** [comment]
Actually, I had to inject `operator_user: dragon` into `/opt/configuration/environments/configuration.yml` to work around this issue.

**Comment by garloff** [comment]
Actually, the file `environments/configuration.yml` has
```
operator_user: dragon
operator_group: dragon
```
since commit d7148ed4 (Christian Berendt, 2019-11-22), so it's unclear where the file with this piece missing is coming from.
I was assuming that we have old, outdated images on quay.io, but 10 months old??? (See issue #400.)

**Comment by berendt** [comment]
Fixed.
