### ISSUE TITLE
Robustness against temporary internet/DNS failure

### ISSUE THREAD

**Issue by garloff** [osism/testbed#394]
During testbed deployments, I saw a few "temporary failure in DNS resolution" issues.
Honestly, I don't know why these happen relatively frequently (more than 1%) these days on CityCloud ...
No retry was done, I had to manually re-rollout the affected playbooks.
Should there be some higher level of robustness against issues by retrying once or twice?

**Comment by berendt** [comment]
```Temporary failure resolving 'de.archive.ubuntu.com'"```

I have the same error. Now and then. This does not seem to be due to Citycloud itself. Seems somehow related to the Ubuntu Mirrors DNS.

**Comment by berendt** [comment]
Should be fixed by #417 and #416.
