### ISSUE TITLE
Allow nested virt on physical installs

### ISSUE THREAD

**Issue by garloff** [osism/testbed#397]
On the compute hosts (HCI nodes), we should have a file `/etc/modprobe.d/kvm.conf` with
```
options kvm_intel nested=1
options kvm_amd nested=1
```
to allow VMs with nested virtualization. This will be useful for self-hosting (putting virtual SCS (testbed) on physical SCS).

**Comment by berendt** [comment]
Is executed by the bootstrap and is not part of the testbed itself.
