### ISSUE TITLE
prometheus alertmanager not accessible

### ISSUE THREAD

**Issue by garloff** [osism/testbed#401]
The docs state that prometheus would be accessible via port 9091. This is not the case in my testbed deployments, even after rolling out all the prometheus playbooks.
Adding
```
prometheus_alertmanager_port: 9091
```
to `/opt/configuration/environments/kolla/configuration.yml` and rolling out prometheus and haproxy again fixed it for me.

**Comment by berendt** [comment]
By default we only use the Prometheus exporters provided by Kolla. We do not deploy the Prometheus server and the Prometheus alert manager.

The Prometheus exporters are integrated in Zabbix. This is used for evaluation.
