### ISSUE TITLE
Test if IPv6 floating IP addresses are usable

### ISSUE THREAD

**Issue by berendt** [osism/testbed#737]

**Comment by osfrickler** [comment]
AFAICT there are no IPv6 FIPs, at least with the upstream Neutron drivers. The strategy should instead be to make globally routed IPv6 addresses available directly for instances within tenant networks, see e.g. https://cloudbau.github.io/openstack/neutron/networking/ipv6/2017/09/11/neutron-pike-ipv6.html

**Comment by berendt** [comment]
Does not work.
