### ISSUE TITLE
docs: check documentation for ease of use

### ISSUE THREAD

**Issue by berendt** [osism/testbed#761]
Before the release 0 of SCS, the documentation of the testbed must be gone through in detail and checked for comprehensibility, completeness, etc. 

Please collect everything that does not fit here in this issue.

**Comment by tibeer** [comment]
First look at the documentation looks good. Some notes I have:
- [ ] The note-box in this section is confusing: https://docs.osism.de/testbed/deployment.html#cloud-resources Do I need 32GB or 104GB memory now?
- [ ] Here https://docs.osism.de/testbed/notes.html seems to be a word missing in this section: *The configuration is intentionally kept quite static. Please no PRs to make the configuration more flexible/dynamic.* Maybe "Please **create** no PRs"?
Practical testing pending though.

**Comment by tibeer** [comment]
Actual testing:
- [ ] Checks are not working until the deployment is complete. This was not clear from documentation. PR to fix this has been created.

**Comment by berendt** [comment]
@tibeer `make check` only works if OpenStack has also been deployed.

**Comment by berendt** [comment]
@tibeer The `make deploy ENVIRONMENT=betacloud PARAMS="-var 'cloud_provider=the-name-of-the-entry'"` part is part of a note explaining how to use the `cloud_provider` parameter. That's fine there.

**Comment by tibeer** [comment]
All resolved for me.

**Comment by garloff** [comment]
If there is noone else reporting anything here, I guess we can close this for now.
Obviously, a new issue can always be opened ...
