### ISSUE TITLE
docs: add instructions to perform updates & upgrades

### ISSUE THREAD

**Issue by berendt** [osism/testbed#762]
In the testbed it should be possible to play through updates & upgrades. Therefore, the documentation should contain appropriate notes on this.

**Comment by garloff** [comment]
Waiting for this for R0 release.

**Comment by berendt** [comment]
This is not a blocker for 1.0.0 as we need something to update to after 1.0.0. Will be added with 2.0.0.

**Comment by garloff** [comment]
Our claim to fame is to be friendly to operators. So one of the things I would want to understand is how I handle the installation of bugfixes/security fixes. The ability to demonstrate this in testbed is very valuable.
My understanding from Tim's description is that you can call ansible playbooks on the management to do exactly that.
Let's make sure it's documented and we're fine for 1.0.0 IMVHO.
