### ISSUE TITLE
Use all mandatory SCS flavour names

### ISSUE THREAD

**Issue by berendt** [osism/testbed#784]

**Comment by garloff** [comment]
Waiting for this for R0 release

**Comment by berendt** [comment]
Small flavours were included: 09f5ee747762553fa6306da93016b399f9c1ca96.

**Comment by berendt** [comment]
@garloff Please check if these flavours are sufficient.

**Comment by berendt** [comment]
More flavors with 27d6d438af022b6b30b15a4088aa36860a3de89b.
