### ISSUE TITLE
Autodetect NIC names and allow overriding

### ISSUE THREAD

**Issue by garloff** [osism/testbed#80]
Like issue#79, just for NIC names.
The first hurdle is for the nodes to get their meta-data, so they can run the user-data script.
On clouds with networked meta-data (rather than ConfigDrive), this means that cloud-init needs to guess correctly the first NIC, bring it up and retrieve the meta-data/user-data. Nothing OSISM testebed can do here, up to the cloud-provider and cloud-init. (But see cloud-init PRs #234 and #235.)

Now we should do:
1. Autodetect NIC names. In some cases, we will have one iface up (by cloud-init) which is the first then. In some cases, the cloud may have provided network_data to us, which should be trusted then. Otherwise, use an heuristic that uses the order of the PCI bus ...
2. We should have the ability to override it from the heat environment if needed. (Heuristics can go wrong ...)

**Comment by garloff** [comment]
In the nodes' runcmd, you still have the assumption hardcoded that all NICs are named ens* and that ens3 is the management network.

**Comment by berendt** [comment]
@garloff Fixed. Can you please test again?
