### ISSUE TITLE
Support ironic

### ISSUE THREAD

**Issue by garloff** [osism/testbed#84]
In SCS deployments, we may have scenarios where the virtualization overhead is too much and does not outweigh the flexibility and sharing that it brings. In that case, we'd still want to manage the hardware with OpenStack and use ironic rather than nova (or go the OTC way, hiding ironic and expose bare-metal flavors via nova).
I suspect that over time, more and more k8s focused deployments will use ironic.
https://metal3.io/blog/2019/10/31/OpenStack-Ironic-and-Bare-Metal-Infrastructure_All-Abstractions-Start-Somewhere.html

Now, ironic in testbed will be interesting, as conceptually, we would ask the underlaying provisioning platform (which is the lower OpenStack) to provide a machine here and then still hook it up to the networks ... of the upper OpenStack. I have to admit that it's not clear to me that there are enough similarities with a production (hardware) setup that we still use testbed to meaningfully explore and test it ... So that would need consideration and we might conclude that ironic would be a non-testbed-only feature.

**Comment by berendt** [comment]
As a first step I have activated the build of the Ironic Images. The Ironic roles are already available.

**Comment by berendt** [comment]
https://github.com/openstack/virtualbmc
