### ISSUE TITLE
failure resolving 'archive.ubuntu.com' => docker: No such file or directory

### ISSUE THREAD

**Issue by Ferenc-** [osism/testbed#885]
In the pluscloud environment it appears to be impossible to get a working deployment with `make deploy-identity`.
Even though other VMs running in the same environment have no trouble resolving `archive.ubuntu.com`,
the osism manager node somehow can't do that, and it ends up in an infinite loop printing 
```
cloud-init[1426]: /root/manager.sh: line 30: /usr/bin/docker: No such file or directory
```
because docker is not installed.

I am attaching the full console log:
[console2.txt](https://github.com/osism/testbed/files/7372904/console2.txt)

**Comment by Ferenc-** [comment]
A fresh deployment still shows the same symptoms, please see the attached log
[console.txt](https://github.com/osism/testbed/files/7485994/console.txt)
the instance is available for inspection here:
https://ui.gx-scs.sovereignit.cloud/project/instances/b46b7748-b678-4740-a37c-e4698b017b61/

**Comment by matfechner** [comment]
Hi @Ferenc- ,

in your tenant at scs setup are two router named testbed,
please remove all legacy components from old deployments,
maybe this disturb a new deployment

**Comment by Ferenc-** [comment]
Hi @matfechner 
This time I made sure that all routers named `testbed` were manually removed, but the symptoms are the same:
https://ui.gx-scs.sovereignit.cloud/project/instances/d08624ac-aae6-41b1-b5e3-fa43d18a6283/

**Comment by frosty-geek** [comment]
Hi @Ferenc-,

 I'm guessing most of the Issues are related to the Testbed MTU Issues (#912 ), can you retry if the Issues are solved for you?

Regards,
Ralf

**Comment by Ferenc-** [comment]
Hi @frosty-geek,

I haven't seen this issue lately. From my side it can be closed. If it resurfaces, then we can re-open.

BR,
FG
