### ISSUE TITLE
netbox: change netbox user to admin

### ISSUE THREAD

**Issue by berendt** [osism/testbed#893]

**Comment by grawert** [comment]
@berendt  The 'admin' user is already documented in the osism documentation.

https://docs.osism.io/appendix/tables/webinterfaces.html

**Comment by berendt** [comment]
@grawert This is the osism/testbed repository with an independent documentation published at https://docs.osism.tech/testbed/. There is still the old user.

Btw. please use osism.tech instead of osism.io. osism.io is the old domain which will be removed in the future.
