### ISSUE TITLE
Use TLS encryption (Kolla)

### ISSUE THREAD

**Issue by berendt** [osism/testbed#897]
* create manager.testbed.osism.xyz -> 196.168.16.5
* create api.testbed.osism.xyz -> 192.168.96.9
* create api-int.testbed.osism.xyz -> 192.168.16.9
* create Letsencrypt productive certificates via dns01 auth
* enable TLS in the testbed

**Comment by berendt** [comment]
Use https://github.com/ctrlaltcoop/certbot-dns-hetzner for the dns01 auth

**Comment by osfrickler** [comment]
The certbot plugin works, but doesn't look to be too well supported. I'd suggest to use https://dns-lexicon.readthedocs.io/en/latest/user_guide.html#let-sencrypt-instructions instead, which I also tested successfully and where I'd also see a better chance to be able to implement support for designate.

**Comment by berendt** [comment]
Domains are available:

* manager.testbed.osism.xyz -> 196.168.16.5
* api.testbed.osism.xyz -> 192.168.96.9
* api-int.testbed.osism.xyz -> 192.168.16.9

**Comment by osfrickler** [comment]
https://github.com/osism/testbed/tree/tls now should implement this with a static locally generated CA cert, since including private keys related to LE certs turned out not to be feasible.

**Comment by berendt** [comment]
Fixed with 0434abbb9857a48cc06d54c7b22d5b2b0d848705
