### ISSUE TITLE
investigate unexpected behaviour on pluscloudopen

### ISSUE THREAD

**Issue by frosty-geek** [osism/testbed#913]
Hi,

we're experiencing unexpected behavior which leads to an unusable testbed while deploying to pluscloudopen. Currently this is under investigation and this issue is for collecting debugging information

errors which may be related to this issue are:
* docker is unable to start container due to "dragon" user being unavaiable
* chrony playbook is unable to install due to unknown reasons
  * swapping apt repos & pkg cache maybe? 
  * why do we swap repos at all?
* manager node loses network connectivity during ansible run & doesn't recover
  * is the config correct?
  

we've tried various terraform version ranging from 1.0.9 - 1.0.11, we will try to limit the tests to 1.0.9. further more we will try to reproduce the behavior with the commands used in the .github/workflows/daily-pluscloudopen.yml and will use the code from the main branch.

Ralf

**Comment by berendt** [comment]
Merged with #912
