### ISSUE TITLE
Use recursive DNS on the control nodes

### ISSUE THREAD

**Issue by berendt** [osism/testbed#934]
Set up a recursive DNS server on the manager and configure both the other nodes and OpenStack networks to use it.

**Comment by frosty-geek** [comment]
Can we describe the use-case for this? 

There are several free high-available [public recursive DNS servers](https://de.wizcase.com/blog/besten-kostenlosen-und-oeffentlichen-dns-server/) available

**Comment by berendt** [comment]
We think that anyone who is a CSP should not depend on an external service that they do not control themselves.

Therefore, we would like to demonstrate in the testbed that a Recursive DNS is not rocket science and can be operated by yourself if required.

**Comment by frosty-geek** [comment]
I agree it's not rocket science but making them as reliable as those public recursive DNS servers is somewhat. 

IMHO if the use-case is the demonstration, I would rather have this service run in a sort of HA/Failover setup and would suggest to move it from the manager to the control nodes (or some other role where node amount is >= 2).

**Comment by osfrickler** [comment]
I don't agree with using the control nodes. In my understanding they should not necessarily have outside connectivity, we are also planning to proxy other external accesses through the manager. For a production setup, I would then expect a redundant setup of manager/service nodes to be in place.

**Comment by berendt** [comment]
Out of scope for the testbed.
