### ISSUE TITLE
openstack-exporter has no data for cinder

### ISSUE THREAD

**Issue by osfrickler** [osism/testbed#965]
Data for volumes and cinder agents is missing in the dashboard.

**Comment by osfrickler** [comment]
Upstream issue https://github.com/openstack-exporter/openstack-exporter/issues/213, will propose a PR to update included gophercloud.

**Comment by osfrickler** [comment]
https://github.com/openstack-exporter/openstack-exporter/pull/215

**Comment by osfrickler** [comment]
Bug in kolla-ansible: https://bugs.launchpad.net/kolla-ansible/+bug/1938194
Proposed fix: https://review.opendev.org/c/openstack/kolla-ansible/+/823397
Confirmed the solution locally, so we don't have to wait for the new exporter version.

**Comment by berendt** [comment]
Approved the Xena + Wallaby backports. Should be fixed tomorrow after the nightly testbed redeployment.
