### ISSUE TITLE
daily-pluscloudopen is failing

### ISSUE THREAD

**Issue by frosty-geek** [osism/testbed#967]
Hi @berendt,

can you have a look why the daily job is failing?

https://github.com/osism/testbed/runs/4439078711?check_suite_focus=true

Is there some old terraform state leftovers or maybe does the new clouds-public.yaml break the credentials due to missing pluscloudopen entries?

regards,
Ralf

**Comment by frosty-geek** [comment]
how i've tested it local:

[daily-pco-test.log](https://github.com/osism/testbed/files/7668973/daily-pco-test.log)

**Comment by berendt** [comment]
We use the Terraform Cloud as the backend for the state and run Terraform there remotely. Seems to be related somehow. Do you have any filters on the API endpoints?

**Comment by frosty-geek** [comment]
Not as far as I'm aware of it.

**Comment by osfrickler** [comment]
I have seen the same error within the testbed deployment in the openstack exporter, so I am assuming an issue with the gophercloud client, will take a closer look.

**Comment by frosty-geek** [comment]
looks like #978 fixed the daily builds

**Comment by frosty-geek** [comment]
sorry i ment to reference #986
