### ISSUE TITLE
"make ssh" does not work in macOS

### ISSUE THREAD

**Issue by amachowiak** [osism/testbed#982]
Hi,

"make ssh" does not work on macOS (at least Big Sur / 11.4) with installed /usr/bin/make. $(USERNAME) in line 157 is evaluated to "".

This results in the following ssh command:
ssh -o StrictHostKeyChecking=no -i .id_rsa.pluscloudopen @n.n.n.n

expected:
ssh -o StrictHostKeyChecking=no -i .id_rsa.pluscloudopen dragon@n.n.n.n

Workaround:
make ssh USERNAME=dragon

Other Make targets are also affected. This is just an example. 

MacOS Make version:
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.

Also tried Brew's version effortless (aka gmake):
GNU Make 4.3
Built for x86_64-apple-darwin20.1.0
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Kind regards,
Andre.

**Comment by berendt** [comment]
Tested with make 3.81 on macOS 12.1. Works.

**Comment by fkr** [comment]
Works on 11.6.2 as well.

```
%> sw_vers                                                                     
ProductName:	macOS
ProductVersion:	11.6.2
BuildVersion:	20G314

%> make -v 
GNU Make 3.81

%> which make
/usr/bin/make

%> make ssh ENVIRONMENT=scs-demo
scs-demo.auto.tfvars
You have new mail.
Last login: Tue Dec 28 17:31:25 2021 from xxx.xxx.xxx.xxx
dragon@testbed-manager:~$
```

**Comment by amachowiak** [comment]
Ah thanks - got the problem!

I copied "local.env.sample" to "local.env" end just replaced "ENVIRONMENT=local" by "ENVIRONMENT=pluscloudopen". 

That's the mistake.

This makes the file looking like this:

ENVIRONMENT=pluscloudopen
CONFIGURATION=
CONSOLE=
OPENSTACK=
USERNAME=

Actually, this resets the defaults that are set in the first 20 lines in Makefile.

A note in local.env.sample might be helpful that unset variables might lead to unexpected behaviour. 

Kind regards,
André.

**Comment by berendt** [comment]
@amachowiak Do you like to do a PR for the note in the local.env.sample file?
